// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckXjKGhHaRngZIbGwhlZCJ9d5v7haNXE',
    appId: '1:763114190977:web:b1853af6a351e15baa3580',
    messagingSenderId: '763114190977',
    projectId: 'tree-72417',
    authDomain: 'tree-72417.firebaseapp.com',
    storageBucket: 'tree-72417.appspot.com',
    measurementId: 'G-MD6CPDHKKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdco4ZPsRmPFMfgtQ9ScmoS4R7WC4crR8',
    appId: '1:763114190977:android:e5fcc9ba60d5f1cdaa3580',
    messagingSenderId: '763114190977',
    projectId: 'tree-72417',
    storageBucket: 'tree-72417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20254fRuokhj57nb9I2zy5mbf0C8piog',
    appId: '1:763114190977:ios:766ec68e3724def2aa3580',
    messagingSenderId: '763114190977',
    projectId: 'tree-72417',
    storageBucket: 'tree-72417.appspot.com',
    iosBundleId: 'com.tree.leaveTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20254fRuokhj57nb9I2zy5mbf0C8piog',
    appId: '1:763114190977:ios:766ec68e3724def2aa3580',
    messagingSenderId: '763114190977',
    projectId: 'tree-72417',
    storageBucket: 'tree-72417.appspot.com',
    iosBundleId: 'com.tree.leaveTracker',
  );
}
